-- Create Profiles table (extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Separate table for Anamnese (Forms)
create table public.anamneses (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  data jsonb not null, -- Stores the entire form object
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Separate table for Fitness Plans (Generated by AI)
create table public.fitness_plans (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  plan_data jsonb not null, -- Stores the JSON plan (dieta, treino, etc)
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.anamneses enable row level security;
alter table public.fitness_plans enable row level security;

-- Policies for Profiles
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

-- Policies for Anamnese
create policy "Users can view own anamnese" on public.anamneses
  for select using (auth.uid() = user_id);

create policy "Users can insert own anamnese" on public.anamneses
  for insert with check (auth.uid() = user_id);

-- Policies for Fitness Plans
create policy "Users can view own plans" on public.fitness_plans
  for select using (auth.uid() = user_id);

create policy "Users can insert own plans" on public.fitness_plans
  for insert with check (auth.uid() = user_id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
